### ISSUE TITLE
Update CSS

### ISSUE THREAD

**Issue by jaakkokorhonen** [okffi/tietopyynto#29]
Update based on https://github.com/stefanw/froide/tree/master/froide/static/css

**Comment by TomiToivio** [comment]
Toihan on nyt käytössä? Vai onko jollain parempia ideoita ulkoasuksi?

**Comment by miskaknapek** [comment]
Sorry about the slow progress.
Have started redrawing the current page-layouts in inDesign. It'll be a lot faster to test different designs if I do it in inDesign than if I do it in CSS. Typographic changes will come once I've redrawn the key screens.
( Have already started using the Open Sans typeface in the re-drawn layouts.)
![screen shot 2014-10-26 at 18 49 36](https://cloud.githubusercontent.com/assets/1816501/4783667/48f8c1f2-5d30-11e4-9545-ca4d97cbc1a2.png)

**Comment by jaakkokorhonen** [comment]
If you just propose minimum possible change for the better for these https://github.com/okffi/tietopyynto/issues?q=assignee%3Amiskaknapek+is%3Aopen, and update the css, @TomiToivio can update it to the server. 

I'm pretty sure we are all in a lot better place already with just that. Maybe just @miskaknapek  leave the drawing to the next phase?

**Comment by TomiToivio** [comment]
Maybe you can add modifications to this file and send it to me? These are the current modifications to default Froide CSS. But there is not too much stuff here yet.

``` css
@import url(http://fonts.googleapis.com/css?family=Ubuntu);
@import url(http://fonts.googleapis.com/css?family=Vollkorn);

#main-folders {
    background-image: url('../img/etusivu.JPG');
    background-size: auto 100%;
    background-repeat: no-repeat;
    opacity:1;  
}
.media {
    padding: 5px;
    border: 1px solid #e3e3e3;                                            
    border-radius: 4px;                                                       
}

#main-folders .row {
    background-color: #ffffff;
    padding-top:10px;
    opacity:0.9;
    border: 1px solid #e3e3e3;
    border-radius: 4px;
}                    

body {
    font-family: 'Ubuntu', sans-serif;
}

#sample-letter {
    font-family: 'Vollkorn', serif;
}

.message {
    font-family: 'Vollkorn', serif;

}

h1, h2, h3, h4, h5, h6, .h1, .h2, .h3, .h4, .h5, .h6 {                         
    font-family: 'Ubuntu', sans-serif;                                         
}
#main-folders h1 {
     margin-top: 0px;
}      
```
